# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 12.x
  ORGANIZATION_KEY: template

jobs:
  testBuildAndRelease:
    name: 'Test, build and release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          always-auth: 'true'

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      # - name: Lint
      #   run: yarn lint

      # - name: Test
      #   run: yarn test
      #   env:
      #     CI: 'true'

      - name: Build
        run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Publish package
        if: contains(github.ref, 'refs/tags/v')
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Slack Notification
        if: always()
        run: |
          yarn global add @bbitgmbh/bbit.slack
          $(yarn global bin)/bslack gha --status ${{ job.status }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BBIT_BOT_TOKEN }}
